TransportationComparison/urls.py
from django.urls import path

from . import views

app_name = 'comparison'

urlpatterns =[
  path('',views.Index, name='index'),
  path('result/<int:trip_output_id>', views.Result, name='result'),
  path('compare/',views.Compare,name='compare'),
  path('autocomplete/', views.autocomplete, name="autocomplete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comparison/', include('TransportationComparison.urls'))
]

TransportationComparison/models.py
from django.db import models

# Create your models here.
class TripInput(models.Model):
  starting_address = models.CharField(max_length = 500) 
  destination_address = models.CharField(max_length = 500)
  start_date = models.DateField()
  end_date = models.DateField()


class TripOutput(models.Model):
  flight_cost = models.FloatField()
  flight_duration = models.FloatField()
  drive_cost = models.FloatField()
  drive_duration = models.FloatField()

  

TransportationComparison/forms.py
from django import forms
from django.conf import settings


class TripForm(forms.Form):
    starting_destination = forms.CharField()
    final_destination = forms.CharField()
    #date_start = forms.DateField(widget = forms.SelectDateWidget)
    #date_end = forms.DateField(widget = forms.SelectDateWidget)
    date_start = forms.DateField()
    date_end = forms.DateField()

TransportationComparison/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import TripOutput
from django.http import Http404
import datetime
from .services import gasApiService
from .forms import TripForm
from django.conf import settings




# Create your views here.


def Index(request):
    template = loader.get_template('index.html')
    form = TripForm()
    context = {'form':form}

    return HttpResponse(template.render(context, request))

def autocomplete(request):       
    return render(request, 'googleMap.html', {'google_maps_api_key': settings.GOOGLE_MAPS_API_KEY})


def Result(request, trip_output_id):
    try:
      trip = TripOutput.objects.get(pk=trip_output_id)
    except TripOutput.DoesNotExist:
      raise Http404("Trip does not exist")
  
    template = loader.get_template('result.html')
    #leemos la base de datos y la guardamos en una variable X
    context = {
        "flightDuration":trip.flight_duration,
        "driveDuration":trip.drive_duration,
        "flightCost":trip.flight_cost,
        "driveCost":trip.drive_cost
    }
    return HttpResponse(template.render(context, request))


def Compare(request):
  # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = TripForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...

            print(form)
            starting_destination = form.data['starting_destination']
            final_destination = form.data['final_destination'] 
            date_start = form.data['date_start']
            date_end = form.data['date_end']
            print(date_start)

    # if a GET (or any other method) we'll create a blank form
    else:
        raise Http404("Form is not valid")



    format_str = '%Y-%m-%d'
    date_start_datetime = datetime.datetime.strptime(date_start, format_str)
    date_end_datetime = datetime.datetime.strptime(date_end, format_str)
    
    duration = date_end_datetime - date_start_datetime
    duration_in_s = duration.total_seconds()  
    hours = divmod(duration_in_s, 3600)[0] 
    gas_price = gasApiService.getGasPricesByUSState()
    print(gas_price) 
    tripOutput = TripOutput(flight_cost=hours*10,drive_cost=hours*5,flight_duration=hours,drive_duration=hours*2)
    tripOutput.save()
    #hacer los api calls;

    #guardar el resultado en un TripOutput con key = tripOutput_id;

    #redireccionar a Result pasando el valor de tripOutput_id;

    #return HttpResponseRedirect(reverse('comparison:results', args=(trip_output.id,)))
    return HttpResponseRedirect(reverse('comparison:result', args=(tripOutput.id, )))

TransportationComparison/templates/googleMap.html
<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Google Autocomplete Address Example</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
</head>
  
<body>
    <div class="container mt-5">
        <h2>Django Google Autocomplete Address Example - Tuts-Station.com</h2>
  
        <div class="form-group">
            <label>Location/City/Address</label>
            <input type="text" name="autocomplete" id="autocomplete" class="form-control" placeholder="Choose Location">
        </div>
  
        <div class="form-group" id="latitudeArea">
            <label>Latitude</label>
            <input type="text" id="latitude" name="latitude" class="form-control">
        </div>
  
        <div class="form-group" id="longtitudeArea">
            <label>Longitude</label>
            <input type="text" name="longitude" id="longitude" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  
    <script type="text/javascript"
        src="https://maps.google.com/maps/api/js?key={{ google_maps_api_key }}&libraries=places" ></script>
    <script>
        $(document).ready(function () {
            $("#latitudeArea").addClass("d-none");
            $("#longtitudeArea").addClass("d-none");
        });
    </script>
    <script>
        google.maps.event.addDomListener(window, 'load', initialize);
  
        function initialize() {
            var input = document.getElementById('autocomplete');
            var autocomplete = new google.maps.places.Autocomplete(input);
  
            autocomplete.addListener('place_changed', function () {
                var place = autocomplete.getPlace();
                $('#latitude').val(place.geometry['location'].lat());
                $('#longitude').val(place.geometry['location'].lng());
  
                $("#latitudeArea").removeClass("d-none");
                $("#longtitudeArea").removeClass("d-none");
            });
        }
    </script>
</body>
</html>

TransportationComparison/templates/index.html
<h1>Drive or Fly</h1>
<form action="{% url 'comparison:compare'%}" method="post">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Search">
</form>

TransportationComparison/templates/result.html
<div>
  <h1 >TEST</h1>
  <h1>{{flightDuration}}</h1>
  <h1>{{driveDuration}}</h1>
  <h1>{{flightCost}}</h1>
  <h1>{{driveCost}}</h1>
</div>